kind: pipeline
name: default

steps:
  - name: build
    image: node:lts
    commands:
      - npm ci
      - npm run build

  - name: deploy
    image: jcodigi/jcodeploy
    settings:
      main: webmaster@pilvi.jco.fi:/var/www/files/jco/jcore-cli-main
      source:
        - bin;.
        - package.json
    environment:
      SSH_KEY:
        from_secret: ssh_key
