package project

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/JCO-Digital/jcore/internal/docker"
	"github.com/JCO-Digital/jcore/internal/logging"
	"github.com/spf13/viper"
)

// SyncPlugins runs the plugin synchronization, either natively from the host via rsync
// or falls back to the container's importplugins script if legacy is true or pluginPullLegacy is configured.
func SyncPlugins(projectDir string, legacy bool) error {
	if legacy || viper.GetBool("pluginPullLegacy") {
		return SyncPluginsLegacy(projectDir)
	}
	return SyncPluginsNative(projectDir)
}

// SyncPluginsLegacy runs the container's importplugins script inside the wordpress container.
func SyncPluginsLegacy(projectDir string) error {
	KnockIfNeeded()
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/importplugins"})
}

// SyncPluginsNative syncs plugins from the remote host to the local wp-content/plugins directory using rsync.
func SyncPluginsNative(projectDir string) error {
	hasCustomScripts := false
	if _, err := os.Stat(filepath.Join(projectDir, "custom-scripts", "plugin-before")); err == nil {
		hasCustomScripts = true
	}
	if _, err := os.Stat(filepath.Join(projectDir, "custom-scripts", "plugin-after")); err == nil {
		hasCustomScripts = true
	}
	if hasCustomScripts {
		logging.Warn("Notice: custom-scripts/plugin-* detected. Set 'pluginPullLegacy = true' in jcore.toml or pass '--legacy' to run legacy in-container scripts.")
	}

	pluginDir := filepath.Join(projectDir, "wp-content", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugins directory: %w", err)
	}

	pluginGit := viper.GetStringSlice("pluginGit")
	if err := WritePluginsGitignore(pluginDir, pluginGit); err != nil {
		logging.Warn("Failed to write plugins .gitignore: %v", err)
	}

	pluginInstall := viper.GetString("pluginInstall")
	if pluginInstall == "composer" || pluginInstall == "local" {
		fmt.Println("Project set to composer or local plugins install, skipping plugins.")
		return nil
	}

	remoteHost := viper.GetString("remoteHost")
	if remoteHost == "" {
		return errors.New("remoteHost is not configured in jcore.toml")
	}
	remotePath := viper.GetString("remotePath")
	if remotePath == "" {
		return errors.New("remotePath is not configured in jcore.toml")
	}

	KnockIfNeeded()

	pluginExclude := viper.GetStringSlice("pluginExclude")
	return RunPluginsRsync(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit)
}

// WritePluginsGitignore generates the wp-content/plugins/.gitignore file from pluginGit.
func WritePluginsGitignore(pluginDir string, pluginGit []string) error {
	var sb strings.Builder
	sb.WriteString("### Autogenerated by jcore-cli, will be overwritten\n")
	for _, p := range pluginGit {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		fmt.Printf("Including /wp-content/plugins/%s in git\n", p)
		sb.WriteString(fmt.Sprintf("!/%s/\n", p))
		sb.WriteString(fmt.Sprintf("!/%s/**\n", p))
	}
	gitignorePath := filepath.Join(pluginDir, ".gitignore")
	return os.WriteFile(gitignorePath, []byte(sb.String()), 0644)
}

// BuildPluginsRsyncArgs constructs the arguments for rsync.
func BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir string, pluginExclude, pluginGit []string) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	sshCmd := "ssh -T -o ConnectTimeout=10"
	if port != "" {
		sshCmd = fmt.Sprintf("ssh -T -o ConnectTimeout=10 -p %s", port)
	}

	args := []string{
		"-r",
		"--delete",
		"--info=progress2",
		"--no-inc-recursive",
		"-e", sshCmd,
		"--exclude=.gitignore",
	}

	allExcludes := append([]string{}, pluginExclude...)
	allExcludes = append(allExcludes, pluginGit...)
	for _, e := range allExcludes {
		e = strings.TrimSpace(e)
		if e != "" {
			fmt.Println(e)
			args = append(args, fmt.Sprintf("--exclude=%s", e))
		}
	}

	src := fmt.Sprintf("%s:%s/wp-content/plugins/", host, strings.TrimRight(remotePath, "/"))
	dest := filepath.Clean(pluginDir) + "/"

	args = append(args, src, dest)
	return args, nil
}

// RunPluginsRsync executes rsync on the host.
func RunPluginsRsync(remoteHost, remotePath, pluginDir string, pluginExclude, pluginGit []string) error {
	if _, err := exec.LookPath("rsync"); err != nil {
		return fmt.Errorf("rsync not found on host: %w (install rsync, or use --legacy to run in container)", err)
	}

	args, err := BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit)
	if err != nil {
		return err
	}

	fmt.Println("Syncing plugins")
	cmd := exec.Command("rsync", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("plugin sync failed: %w", err)
	}

	fmt.Println("Plugins synced")
	return nil
}

// SyncMedia runs the container's importmedia script, which rsyncs uploads
// from the configured remote host.
func SyncMedia(projectDir string) error {
	KnockIfNeeded()
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/importmedia"})
}

// InstallLocalPlugins runs the container's installplugins script, which
// installs and activates every plugin listed in pluginLocal.
func InstallLocalPlugins(projectDir string) error {
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/installplugins"})
}
