package project

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestWritePluginsGitignore(t *testing.T) {
	tmpDir := t.TempDir()

	pluginGit := []string{"lohko", "jcore-dynamic-archive", "jcore-turva"}
	if err := WritePluginsGitignore(tmpDir, pluginGit); err != nil {
		t.Fatalf("WritePluginsGitignore failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, ".gitignore"))
	if err != nil {
		t.Fatalf("failed to read .gitignore: %v", err)
	}

	expectedLines := []string{
		"### Autogenerated by jcore-cli, will be overwritten",
		"!/lohko/",
		"!/lohko/**",
		"!/jcore-dynamic-archive/",
		"!/jcore-dynamic-archive/**",
		"!/jcore-turva/",
		"!/jcore-turva/**",
	}

	actual := string(content)
	for _, line := range expectedLines {
		if !strings.Contains(actual, line) {
			t.Errorf("expected .gitignore to contain %q, but got:\n%s", line, actual)
		}
	}
}

func TestBuildPluginsRsyncArgs(t *testing.T) {
	remoteHost := "user@server.example.com:2222"
	remotePath := "/var/www/site"
	pluginDir := "/tmp/project/wp-content/plugins"
	pluginExclude := []string{"mainwp-child", "ruudukko"}
	pluginGit := []string{"lohko"}

	args, err := BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit)
	if err != nil {
		t.Fatalf("BuildPluginsRsyncArgs failed: %v", err)
	}

	// Verify -e ssh command contains port 2222 and ConnectTimeout=10
	eIdx := slices.Index(args, "-e")
	if eIdx == -1 || eIdx+1 >= len(args) {
		t.Fatalf("expected -e flag in rsync args: %v", args)
	}
	sshCmd := args[eIdx+1]
	if !strings.Contains(sshCmd, "-p 2222") || !strings.Contains(sshCmd, "ConnectTimeout=10") {
		t.Errorf("expected sshCmd to contain '-p 2222' and 'ConnectTimeout=10', got %q", sshCmd)
	}

	// Verify excludes
	expectedExcludes := []string{
		"--exclude=.gitignore",
		"--exclude=mainwp-child",
		"--exclude=ruudukko",
		"--exclude=lohko",
	}
	for _, exc := range expectedExcludes {
		if !slices.Contains(args, exc) {
			t.Errorf("expected %q in args, got %v", exc, args)
		}
	}

	// Verify source and dest
	expectedSrc := "user@server.example.com:/var/www/site/wp-content/plugins/"
	expectedDest := "/tmp/project/wp-content/plugins/"
	if args[len(args)-2] != expectedSrc {
		t.Errorf("expected src %q, got %q", expectedSrc, args[len(args)-2])
	}
	if args[len(args)-1] != expectedDest {
		t.Errorf("expected dest %q, got %q", expectedDest, args[len(args)-1])
	}
}
