package project

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/AlecAivazis/survey/v2"
	"github.com/JCO-Digital/jcore/internal/docker"
	"github.com/JCO-Digital/jcore/internal/logging"
	"github.com/spf13/viper"
)

var yearRegex = regexp.MustCompile(`^\d{4}$`)

// SyncPlugins runs the plugin synchronization, either natively from the host via rsync
// or falls back to the container's importplugins script if legacy is true or pluginPullLegacy is configured.
func SyncPlugins(projectDir string, legacy bool) error {
	if legacy || viper.GetBool("pluginPullLegacy") {
		return SyncPluginsLegacy(projectDir)
	}
	return SyncPluginsNative(projectDir)
}

// SyncPluginsLegacy runs the container's importplugins script inside the wordpress container.
func SyncPluginsLegacy(projectDir string) error {
	KnockIfNeeded()
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/importplugins"})
}

// SyncPluginsNative syncs plugins from the remote host to the local wp-content/plugins directory using rsync.
func SyncPluginsNative(projectDir string) error {
	// Execute custom before-script inside container if present
	if err := RunCustomScript(projectDir, "plugin-before"); err != nil {
		return err
	}

	pluginDir := filepath.Join(projectDir, "wp-content", "plugins")
	if err := os.MkdirAll(pluginDir, 0755); err != nil {
		return fmt.Errorf("failed to create plugins directory: %w", err)
	}

	pluginGit := viper.GetStringSlice("pluginGit")
	if err := WritePluginsGitignore(pluginDir, pluginGit); err != nil {
		logging.Warn("Failed to write plugins .gitignore: %v", err)
	}

	pluginInstall := viper.GetString("pluginInstall")
	if pluginInstall == "composer" || pluginInstall == "local" {
		fmt.Println("Project set to composer or local plugins install, skipping plugins.")
		return nil
	}

	remoteHost := viper.GetString("remoteHost")
	if remoteHost == "" {
		return errors.New("remoteHost is not configured in jcore.toml")
	}
	remotePath := viper.GetString("remotePath")
	if remotePath == "" {
		return errors.New("remotePath is not configured in jcore.toml")
	}

	KnockIfNeeded()

	pluginExclude := viper.GetStringSlice("pluginExclude")
	if err := RunPluginsRsync(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit); err != nil {
		return err
	}

	// Execute custom after-script inside container if present
	if err := RunCustomScript(projectDir, "plugin-after"); err != nil {
		return err
	}

	return nil
}

// WritePluginsGitignore generates the wp-content/plugins/.gitignore file from pluginGit.
func WritePluginsGitignore(pluginDir string, pluginGit []string) error {
	var sb strings.Builder
	sb.WriteString("### Autogenerated by jcore-cli, will be overwritten\n")
	for _, p := range pluginGit {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		fmt.Printf("Including /wp-content/plugins/%s in git\n", p)
		sb.WriteString(fmt.Sprintf("!/%s/\n", p))
		sb.WriteString(fmt.Sprintf("!/%s/**\n", p))
	}
	gitignorePath := filepath.Join(pluginDir, ".gitignore")
	return os.WriteFile(gitignorePath, []byte(sb.String()), 0644)
}

// BuildPluginsRsyncArgs constructs the arguments for rsync.
func BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir string, pluginExclude, pluginGit []string) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	sshCmd := "ssh -T -o ConnectTimeout=10"
	if port != "" {
		sshCmd = fmt.Sprintf("ssh -T -o ConnectTimeout=10 -p %s", port)
	}

	args := []string{
		"-r",
		"--delete",
		"--info=progress2",
		"--no-inc-recursive",
		"-e", sshCmd,
		"--exclude=.gitignore",
	}

	allExcludes := append([]string{}, pluginExclude...)
	allExcludes = append(allExcludes, pluginGit...)
	for _, e := range allExcludes {
		e = strings.TrimSpace(e)
		if e != "" {
			fmt.Println(e)
			args = append(args, fmt.Sprintf("--exclude=%s", e))
		}
	}

	src := fmt.Sprintf("%s:%s/wp-content/plugins/", host, strings.TrimRight(remotePath, "/"))
	dest := filepath.Clean(pluginDir) + "/"

	args = append(args, src, dest)
	return args, nil
}

// RunPluginsRsync executes rsync on the host.
func RunPluginsRsync(remoteHost, remotePath, pluginDir string, pluginExclude, pluginGit []string) error {
	if _, err := exec.LookPath("rsync"); err != nil {
		return fmt.Errorf("rsync not found on host: %w (install rsync, or use --legacy to run in container)", err)
	}

	args, err := BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit)
	if err != nil {
		return err
	}

	fmt.Println("Syncing plugins")
	cmd := exec.Command("rsync", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("plugin sync failed: %w", err)
	}

	fmt.Println("Plugins synced")
	return nil
}

// SyncMedia runs the media synchronization, either natively from the host via rsync
// (with interactive upload folder selection) or falls back to the container's importmedia
// script if legacy is true or mediaPullLegacy is configured.
func SyncMedia(projectDir string, legacy bool) error {
	if legacy || viper.GetBool("mediaPullLegacy") {
		return SyncMediaLegacy(projectDir)
	}
	return SyncMediaNative(projectDir)
}

// SyncMediaLegacy runs the container's importmedia script inside the wordpress container.
func SyncMediaLegacy(projectDir string) error {
	KnockIfNeeded()
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/importmedia"})
}

// SyncMediaNative syncs uploads from the remote host to wp-content/uploads using rsync,
// optionally presenting an interactive folder selection if running in an interactive terminal.
func SyncMediaNative(projectDir string) error {
	// Execute custom before-script inside container if present
	if err := RunCustomScript(projectDir, "media-before"); err != nil {
		return err
	}

	uploadsDir := filepath.Join(projectDir, "wp-content", "uploads")
	if err := os.MkdirAll(uploadsDir, 0755); err != nil {
		return fmt.Errorf("failed to create uploads directory: %w", err)
	}

	remoteHost := viper.GetString("remoteHost")
	if remoteHost == "" {
		return errors.New("remoteHost is not configured in jcore.toml")
	}
	remotePath := viper.GetString("remotePath")
	if remotePath == "" {
		return errors.New("remotePath is not configured in jcore.toml")
	}

	KnockIfNeeded()

	var selectedFolders []string
	var totalFolders int

	// In an interactive terminal, fetch remote upload folders and prompt user
	if isTerminal() {
		fmt.Println("Discovering remote upload folders...")
		folders, err := FetchRemoteUploadFolders(remoteHost, remotePath)
		if err != nil {
			logging.Verbose("Could not list remote upload folders: %v (syncing all)", err)
		} else if len(folders) > 0 {
			totalFolders = len(folders)
			sorted := SortUploadFolders(folders)
			selected, err := PromptSelectUploadFolders(sorted)
			if err != nil {
				return err
			}
			if len(selected) == 0 {
				fmt.Println("No upload folders selected, skipping media sync.")
				return nil
			}
			selectedFolders = selected
		}
	}

	if err := RunMediaRsync(remoteHost, remotePath, uploadsDir, selectedFolders, totalFolders); err != nil {
		return err
	}

	// Execute custom after-script inside container if present
	if err := RunCustomScript(projectDir, "media-after"); err != nil {
		return err
	}

	return nil
}

// FetchRemoteUploadFolders queries the remote server via SSH to list the immediate subfolders of wp-content/uploads.
func FetchRemoteUploadFolders(remoteHost, remotePath string) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	remoteCmd := fmt.Sprintf("cd '%s/wp-content/uploads' 2>/dev/null && for d in */; do [ -d \"$d\" ] && echo \"${d%%/}\"; done", strings.TrimRight(remotePath, "/"))

	sshArgs := []string{
		"-T",
		"-o", "ConnectTimeout=10",
	}
	if port != "" {
		sshArgs = append(sshArgs, "-p", port)
	}
	sshArgs = append(sshArgs, host, remoteCmd)

	cmd := exec.Command("ssh", sshArgs...)
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var folders []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && line != "wp-migrate-db" {
			folders = append(folders, line)
		}
	}
	return folders, nil
}

// SortUploadFolders sorts year folders (e.g. 2026, 2025, 2024) descending first,
// followed by other folders alphabetically.
func SortUploadFolders(folders []string) []string {
	var years []string
	var others []string

	for _, f := range folders {
		if yearRegex.MatchString(f) {
			years = append(years, f)
		} else {
			others = append(others, f)
		}
	}

	// Sort years descending (newest first)
	sort.Slice(years, func(i, j int) bool {
		return years[i] > years[j]
	})

	// Sort others alphabetically
	sort.Strings(others)

	return append(years, others...)
}

// PromptSelectUploadFolders presents an interactive checklist for the user to select which folders to sync.
func PromptSelectUploadFolders(folders []string) ([]string, error) {
	var selected []string
	prompt := &survey.MultiSelect{
		Message:  "Select upload folders to sync:",
		Options:  folders,
		Default:  folders, // pre-select all so Enter syncs everything
		PageSize: 15,
	}
	if err := survey.AskOne(prompt, &selected); err != nil {
		return nil, err
	}
	return selected, nil
}

// BuildMediaRsyncArgs constructs the arguments for media rsync.
func BuildMediaRsyncArgs(remoteHost, remotePath, uploadsDir string, selectedFolders []string, totalFolderCount int) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	sshCmd := "ssh -T -o ConnectTimeout=10"
	if port != "" {
		sshCmd = fmt.Sprintf("ssh -T -o ConnectTimeout=10 -p %s", port)
	}

	args := []string{
		"-r",
		"--delete",
		"--info=progress2",
		"--no-inc-recursive",
		"-e", sshCmd,
		"--exclude=wp-migrate-db",
	}

	// If a subset of folders was selected, include those folders and exclude other dirs
	if len(selectedFolders) > 0 && (totalFolderCount == 0 || len(selectedFolders) < totalFolderCount) {
		for _, folder := range selectedFolders {
			folder = strings.TrimSpace(folder)
			if folder != "" {
				args = append(args, fmt.Sprintf("--include=%s/***", folder))
			}
		}
		// Exclude all other subdirectories in uploads
		args = append(args, "--exclude=*/")
	}

	src := fmt.Sprintf("%s:%s/wp-content/uploads/", host, strings.TrimRight(remotePath, "/"))
	dest := filepath.Clean(uploadsDir) + "/"

	args = append(args, src, dest)
	return args, nil
}

// RunMediaRsync executes rsync for wp-content/uploads on the host.
func RunMediaRsync(remoteHost, remotePath, uploadsDir string, selectedFolders []string, totalFolderCount int) error {
	if _, err := exec.LookPath("rsync"); err != nil {
		return fmt.Errorf("rsync not found on host: %w (install rsync, or use --legacy to run in container)", err)
	}

	args, err := BuildMediaRsyncArgs(remoteHost, remotePath, uploadsDir, selectedFolders, totalFolderCount)
	if err != nil {
		return err
	}

	fmt.Println("Syncing media")
	cmd := exec.Command("rsync", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("media sync failed: %w", err)
	}

	fmt.Println("Media synced")
	return nil
}

func isTerminal() bool {
	fi, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return (fi.Mode() & os.ModeCharDevice) != 0
}

// InstallLocalPlugins runs the container's installplugins script, which
// installs and activates every plugin listed in pluginLocal.
func InstallLocalPlugins(projectDir string) error {
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/installplugins"})
}

// SyncThemes runs theme synchronization, either natively from the host via rsync
// (with interactive theme folder selection) or falls back to the container's importthemes
// script if legacy is true or themePullLegacy is configured.
func SyncThemes(projectDir string, legacy bool) error {
	if legacy || viper.GetBool("themePullLegacy") {
		return SyncThemesLegacy(projectDir)
	}
	return SyncThemesNative(projectDir)
}

// SyncThemesLegacy runs the container's importthemes script inside the wordpress container.
func SyncThemesLegacy(projectDir string) error {
	KnockIfNeeded()
	return docker.ComposeExec(projectDir, "wordpress", []string{"/project/.config/scripts/importthemes"})
}

// SyncThemesNative syncs themes from the remote host to wp-content/themes using rsync,
// optionally presenting an interactive folder selection if running in an interactive terminal.
func SyncThemesNative(projectDir string) error {
	// Execute custom before-script inside container if present
	if err := RunCustomScript(projectDir, "theme-before"); err != nil {
		return err
	}

	themesDir := filepath.Join(projectDir, "wp-content", "themes")
	if err := os.MkdirAll(themesDir, 0755); err != nil {
		return fmt.Errorf("failed to create themes directory: %w", err)
	}

	remoteHost := viper.GetString("remoteHost")
	if remoteHost == "" {
		return errors.New("remoteHost is not configured in jcore.toml")
	}
	remotePath := viper.GetString("remotePath")
	if remotePath == "" {
		return errors.New("remotePath is not configured in jcore.toml")
	}

	KnockIfNeeded()

	var selectedThemes []string
	var totalThemes int

	// In an interactive terminal, fetch remote theme folders and prompt user
	if isTerminal() {
		fmt.Println("Discovering remote theme folders...")
		folders, err := FetchRemoteThemeFolders(remoteHost, remotePath)
		if err != nil {
			logging.Verbose("Could not list remote theme folders: %v (syncing all)", err)
		} else if len(folders) > 0 {
			totalThemes = len(folders)
			sort.Strings(folders)
			selected, err := PromptSelectThemeFolders(folders)
			if err != nil {
				return err
			}
			if len(selected) == 0 {
				fmt.Println("No theme folders selected, skipping theme sync.")
				return nil
			}
			selectedThemes = selected
		}
	}

	if err := RunThemesRsync(remoteHost, remotePath, themesDir, selectedThemes, totalThemes); err != nil {
		return err
	}

	// Execute custom after-script inside container if present
	if err := RunCustomScript(projectDir, "theme-after"); err != nil {
		return err
	}

	return nil
}

// FetchRemoteThemeFolders queries the remote server via SSH to list the immediate subfolders of wp-content/themes.
func FetchRemoteThemeFolders(remoteHost, remotePath string) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	remoteCmd := fmt.Sprintf("cd '%s/wp-content/themes' 2>/dev/null && for d in */; do [ -d \"$d\" ] && echo \"${d%%%%/}\"; done", strings.TrimRight(remotePath, "/"))

	sshArgs := []string{
		"-T",
		"-o", "ConnectTimeout=10",
	}
	if port != "" {
		sshArgs = append(sshArgs, "-p", port)
	}
	sshArgs = append(sshArgs, host, remoteCmd)

	cmd := exec.Command("ssh", sshArgs...)
	out, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	var folders []string
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line != "" && !strings.HasPrefix(line, "twenty") {
			folders = append(folders, line)
		}
	}
	return folders, nil
}

// PromptSelectThemeFolders presents an interactive checklist for the user to select which themes to sync.
func PromptSelectThemeFolders(folders []string) ([]string, error) {
	var selected []string
	prompt := &survey.MultiSelect{
		Message:  "Select theme folders to sync:",
		Options:  folders,
		PageSize: 15,
	}
	if err := survey.AskOne(prompt, &selected); err != nil {
		return nil, err
	}
	return selected, nil
}

// BuildThemesRsyncArgs constructs the arguments for theme rsync.
func BuildThemesRsyncArgs(remoteHost, remotePath, themesDir string, selectedThemes []string, totalThemeCount int) ([]string, error) {
	host, port := ParseSSHHostPort(remoteHost)
	if host == "" {
		return nil, errors.New("remoteHost is empty")
	}
	if remotePath == "" {
		return nil, errors.New("remotePath is empty")
	}

	sshCmd := "ssh -T -o ConnectTimeout=10"
	if port != "" {
		sshCmd = fmt.Sprintf("ssh -T -o ConnectTimeout=10 -p %s", port)
	}

	args := []string{
		"-r",
		"--delete",
		"--info=progress2",
		"--no-inc-recursive",
		"-e", sshCmd,
		"--exclude=twenty*",
	}

	// If a subset of themes was selected, include those themes and exclude other dirs
	if len(selectedThemes) > 0 && (totalThemeCount == 0 || len(selectedThemes) < totalThemeCount) {
		for _, theme := range selectedThemes {
			theme = strings.TrimSpace(theme)
			if theme != "" {
				args = append(args, fmt.Sprintf("--include=%s/***", theme))
			}
		}
		// Exclude all other subdirectories in themes
		args = append(args, "--exclude=*/")
	}

	src := fmt.Sprintf("%s:%s/wp-content/themes/", host, strings.TrimRight(remotePath, "/"))
	dest := filepath.Clean(themesDir) + "/"

	args = append(args, src, dest)
	return args, nil
}

// RunThemesRsync executes rsync for wp-content/themes on the host.
func RunThemesRsync(remoteHost, remotePath, themesDir string, selectedThemes []string, totalThemeCount int) error {
	if _, err := exec.LookPath("rsync"); err != nil {
		return fmt.Errorf("rsync not found on host: %w (install rsync, or use --legacy to run in container)", err)
	}

	args, err := BuildThemesRsyncArgs(remoteHost, remotePath, themesDir, selectedThemes, totalThemeCount)
	if err != nil {
		return err
	}

	fmt.Println("Syncing themes")
	cmd := exec.Command("rsync", args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("theme sync failed: %w", err)
	}

	fmt.Println("Themes synced")
	return nil
}
