package project

import (
	"os"
	"path/filepath"
	"reflect"
	"slices"
	"strings"
	"testing"
)

func TestWritePluginsGitignore(t *testing.T) {
	tmpDir := t.TempDir()

	pluginGit := []string{"lohko", "jcore-dynamic-archive", "jcore-turva"}
	if err := WritePluginsGitignore(tmpDir, pluginGit); err != nil {
		t.Fatalf("WritePluginsGitignore failed: %v", err)
	}

	content, err := os.ReadFile(filepath.Join(tmpDir, ".gitignore"))
	if err != nil {
		t.Fatalf("failed to read .gitignore: %v", err)
	}

	expectedLines := []string{
		"### Autogenerated by jcore-cli, will be overwritten",
		"!/lohko/",
		"!/lohko/**",
		"!/jcore-dynamic-archive/",
		"!/jcore-dynamic-archive/**",
		"!/jcore-turva/",
		"!/jcore-turva/**",
	}

	actual := string(content)
	for _, line := range expectedLines {
		if !strings.Contains(actual, line) {
			t.Errorf("expected .gitignore to contain %q, but got:\n%s", line, actual)
		}
	}
}

func TestBuildPluginsRsyncArgs(t *testing.T) {
	remoteHost := "user@server.example.com:2222"
	remotePath := "/var/www/site"
	pluginDir := "/tmp/project/wp-content/plugins"
	pluginExclude := []string{"mainwp-child", "ruudukko"}
	pluginGit := []string{"lohko"}

	args, err := BuildPluginsRsyncArgs(remoteHost, remotePath, pluginDir, pluginExclude, pluginGit)
	if err != nil {
		t.Fatalf("BuildPluginsRsyncArgs failed: %v", err)
	}

	// Verify -e ssh command contains port 2222 and ConnectTimeout=10
	eIdx := slices.Index(args, "-e")
	if eIdx == -1 || eIdx+1 >= len(args) {
		t.Fatalf("expected -e flag in rsync args: %v", args)
	}
	sshCmd := args[eIdx+1]
	if !strings.Contains(sshCmd, "-p 2222") || !strings.Contains(sshCmd, "ConnectTimeout=10") {
		t.Errorf("expected sshCmd to contain '-p 2222' and 'ConnectTimeout=10', got %q", sshCmd)
	}

	// Verify excludes
	expectedExcludes := []string{
		"--exclude=.gitignore",
		"--exclude=mainwp-child",
		"--exclude=ruudukko",
		"--exclude=lohko",
	}
	for _, exc := range expectedExcludes {
		if !slices.Contains(args, exc) {
			t.Errorf("expected %q in args, got %v", exc, args)
		}
	}

	// Verify source and dest
	expectedSrc := "user@server.example.com:/var/www/site/wp-content/plugins/"
	expectedDest := "/tmp/project/wp-content/plugins/"
	if args[len(args)-2] != expectedSrc {
		t.Errorf("expected src %q, got %q", expectedSrc, args[len(args)-2])
	}
	if args[len(args)-1] != expectedDest {
		t.Errorf("expected dest %q, got %q", expectedDest, args[len(args)-1])
	}
}

func TestSortUploadFolders(t *testing.T) {
	input := []string{"2021", "woocommerce_uploads", "2024", "elementor", "2026", "2020", "cache"}
	expected := []string{"2026", "2024", "2021", "2020", "cache", "elementor", "woocommerce_uploads"}

	actual := SortUploadFolders(input)
	if !reflect.DeepEqual(actual, expected) {
		t.Errorf("SortUploadFolders() = %v, want %v", actual, expected)
	}
}

func TestBuildMediaRsyncArgs_FullSync(t *testing.T) {
	remoteHost := "user@server.example.com"
	remotePath := "/var/www/site"
	uploadsDir := "/tmp/project/wp-content/uploads"
	folders := []string{"2025", "2026"}

	// When all folders are selected, no --include/--exclude=*/ rules should be added
	args, err := BuildMediaRsyncArgs(remoteHost, remotePath, uploadsDir, folders, 2)
	if err != nil {
		t.Fatalf("BuildMediaRsyncArgs failed: %v", err)
	}

	if slices.Contains(args, "--exclude=*/") {
		t.Errorf("expected full sync to not contain '--exclude=*/', got %v", args)
	}
	if !slices.Contains(args, "--exclude=wp-migrate-db") {
		t.Errorf("expected '--exclude=wp-migrate-db' in args, got %v", args)
	}
}

func TestBuildMediaRsyncArgs_FilteredSync(t *testing.T) {
	remoteHost := "user@server.example.com:2222"
	remotePath := "/var/www/site"
	uploadsDir := "/tmp/project/wp-content/uploads"
	selected := []string{"2026", "woocommerce_uploads"}

	// 2 of 5 folders selected
	args, err := BuildMediaRsyncArgs(remoteHost, remotePath, uploadsDir, selected, 5)
	if err != nil {
		t.Fatalf("BuildMediaRsyncArgs failed: %v", err)
	}

	expectedIncludes := []string{
		"--include=2026/***",
		"--include=woocommerce_uploads/***",
		"--exclude=*/",
	}
	for _, inc := range expectedIncludes {
		if !slices.Contains(args, inc) {
			t.Errorf("expected %q in args, got %v", inc, args)
		}
	}

	// Verify source and dest
	expectedSrc := "user@server.example.com:/var/www/site/wp-content/uploads/"
	expectedDest := "/tmp/project/wp-content/uploads/"
	if args[len(args)-2] != expectedSrc {
		t.Errorf("expected src %q, got %q", expectedSrc, args[len(args)-2])
	}
	if args[len(args)-1] != expectedDest {
		t.Errorf("expected dest %q, got %q", expectedDest, args[len(args)-1])
	}
}
